[package]
name = "zkwasm-rlp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }
rlp = { version = "0.5.2", default-features = false }
wasm-bindgen = "0.2.83"
reth-primitives = {git = "https://github.com/paradigmxyz/reth", rev="v0.1.0-alpha.8", features = [
    "arbitrary",
    "test-utils",
]}
bytes = "1.4.0"
quote = "1.0.33"
